# Provision AWS EKS cluster
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: dan-ecommerce
  type: core.Directory
  children:
  - name: aws-dan-ecommerce
    type: aws.Cloud
    accesskey: !value AWSAccessKey
    accessSecret: !value AWSAccessSecret
    children:
    - name: eks-cloudformation
      type: aws.cloudformation.Stack
      region: us-east-2
---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: dan-ecommerce
  type: core.Directory
  children:
  - name: aws-cloudformation-dan-ecommerce
    type: udm.Environment
    members:
    - Infrastructure/dan-ecommerce/aws-dan-ecommerce
    - Infrastructure/dan-ecommerce/aws-dan-ecommerce/eks-cloudformation